### PR TITLE
MIST-563 Add LogReturnedErr convenience method

### PR DESCRIPTION
**Pull request by bbickerton**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-logrus-ext/4)

### CODE REVIEW

**Comment by bbickerton** [comment]
Ok to test

**Comment by mmlb** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[ext.go, line 29 [r1]](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/4#-JyNr0aIxdl9tmHNm8eJ)** ([raw file](https://github.com/mistifyio/mistify-logrus-ext/blob/921ce9e4d102183f73ba134334c5adc24fa3e82f/ext.go#L29)):</sup>
comment is a bad example, fields and message are missing

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/4)

**Comment by bbickerton** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[ext.go, line 29 [r1]](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/4#-JyNr0aIxdl9tmHNm8eJ)** ([raw file](https://github.com/mistifyio/mistify-logrus-ext/blob/921ce9e4d102183f73ba134334c5adc24fa3e82f/ext.go#L29)):</sup>
Forgot to update that when I changed the function signature. Fixed

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/4)

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/4)

**Comment by bbickerton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[ext.go, line 29 [r1]](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/4#-JyNr0aIxdl9tmHNm8eJ)** ([raw file](https://github.com/mistifyio/mistify-logrus-ext/blob/921ce9e4d102183f73ba134334c5adc24fa3e82f/ext.go#L29)):</sup>
Done.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/4)

**Pull request merged**
