### PR TITLE
MIST-220 Golint and documentation

### PR DESCRIPTION
**Pull request by bbickerton**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-logrus-ext/2)

### CODE REVIEW

**Comment by mmlb** [comment]
seems like you commited demo/demo binary, you should nuke it and rebase so it's not in history, and add to .gitignore while you are at it

---

Reviewed files:
- demo/main.go @ r1
- ext.go @ r1
- formatter.go @ r1

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/2)

**Comment by bbickerton** [comment]
Whoops, good catch. 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/2)

**Comment by bbickerton** [comment]
Done. It shows up as an empty file in Reviewable, but it's gone from the Github PR page.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/2)

**Comment by mmlb** [comment]
Reviewed files:
- demo/.gitignore @ r2
- demo/demo @ r2

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/2)

**Pull request merged**
