### PR TITLE
MIST-591 Switch to testify and improve test code coverage

### PR DESCRIPTION
**Pull request by bbickerton**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-logrus-ext/6)

### CODE REVIEW

**Comment by trisk** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/6)

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[ext_test.go, line 87 [r1]](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/6#-Jyif0TGtEPsu8R0QwFL)** ([raw file](https://github.com/mistifyio/mistify-logrus-ext/blob/1daf9731527261568e789fe10e03fc095d095dc1/ext_test.go#L87)):</sup>
should out be empty?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/6)

**Comment by bbickerton** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[ext_test.go, line 87 [r1]](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/6#-Jyif0TGtEPsu8R0QwFL)** ([raw file](https://github.com/mistifyio/mistify-logrus-ext/blob/1daf9731527261568e789fe10e03fc095d095dc1/ext_test.go#L87)):</sup>
That would indeed be a simpler assertion. Fixed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/6)

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[ext_test.go, line 87 [r1]](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/6#-Jyif0TGtEPsu8R0QwFL)** ([raw file](https://github.com/mistifyio/mistify-logrus-ext/blob/1daf9731527261568e789fe10e03fc095d095dc1/ext_test.go#L87)):</sup>
lol

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-logrus-ext/6)

**Comment by bbickerton** [comment]
Ok to test

**Pull request merged**
